<a href="https://colab.research.google.com/github/cloht/cloht/blob/main/python_study_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#dict
d={}

In [ ]:
#list comprehension
m=[i**2 for i in range(5)]
list(range(0,8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
#vetor 변경헀을때 영향 안 받는 법
v=[1,5,3,10,2]
from copy import deepcopy
m=3*[deepcopy(v)]
m

[[1, 5, 3, 10, 2], [1, 5, 3, 10, 2], [1, 5, 3, 10, 2]]

#*LIST ARRAY*


In [8]:
#array클래스
#파이썬 리스트는 ['ss',2,10]다 가능하지만 np는 1가지 자료형만 가능
v=[0.75,1.0,0.5,1.25,1.75]
import array
a=array.array('f',v)
a.append(0.25)
a.tolist()

[0.75, 1.0, 0.5, 1.25, 1.75, 0.25]

In [14]:
#array 읽기 저장 기능
f=open('array.apy','wb')
a.tofile(f)
f.close()

#with 문 활용
with open('array.apy','wb') as f:
  a.tofile(f)


# *NUMPY ARRAY*


In [15]:
#basic,num
import numpy as np
a=np.array([0,0.5,1.0,1.5,2.0])
a


array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
type(a)

numpy.ndarray

In [17]:
#num
a=np.array(['a','b','c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [18]:
#arange
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
#float_arange
a=np.arange(8,dtype=float)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [23]:
#index_a
a[4:]

array([4., 5., 6., 7.])

In [28]:
#function_a
a.sum()
a.std()
a.cumsum()

np.float64(2.29128784747792)

In [29]:
#list_array np_array 차이
l=[0.,0.5,1.5]
2*l

[0.0, 0.5, 1.5, 0.0, 0.5, 1.5]

In [32]:
#np는 수학연산 가능
#list는 불가능함
2*a
2**a
a**2
a**a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

#ufunc의 사용


#다차원


In [38]:
b=np.array([a,a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [39]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [40]:
b[0,2]

np.float64(2.0)

In [41]:
b[:,2]

array([2., 4.])

In [42]:
b.sum()

np.float64(84.0)

In [44]:
b.sum(axis=0)
b.sum(axis=1)

array([28., 56.])

#ndarray 객체 만드는법


In [45]:
#1.np.array()
#2.np.zero등 임의의 수 넣기
c=np.zeros((2,3,4),dtype='i',order='C')
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [49]:
c=np.ones((2,3,4),dtype='i',order='C')
d=np.ones_like(c,dtype='f')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [50]:
d=np.zeros_like(c,dtype='f')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [53]:
e=np.empty((2,3,4))
e

array([[[    nan,     nan, 0.e+000,     nan],
        [5.e-324,     nan, 1.e-323,     nan],
        [5.e-324, 0.e+000, 1.e-323, 5.e-324]],

       [[5.e-324, 1.e-323, 0.e+000, 5.e-324],
        [    nan, 1.e-323,     nan, 5.e-324],
        [    nan, 0.e+000,     nan,     nan]]])

In [54]:
f=np.empty_like(c)
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [59]:
g=np.linspace(5,15,12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

# 추가 정보


In [60]:
g.size

12

In [61]:
g.itemsize

8

In [62]:
g.ndim

1

In [63]:
g.shape

(12,)

In [64]:
g.dtype

dtype('float64')

In [65]:
g.nbytes

96

#형태 변환 크기 변환


In [67]:
#형태 변환
#개수 변화 없음
g=np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
g.shape
np.shape(g)

(15,)

In [78]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
h=g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [81]:
h.T
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [ ]:
#크기 변환
#개수 변화 있음

In [82]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
#다운 사이즈
np.resize(g,(1,3))
np.resize(g,(2,1))

array([[0],
       [1]])

In [86]:
#업 사이즈
np.resize(g,(5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [87]:
#stack 덧 붙일때
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [88]:
np.hstack((h,2*h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [89]:
np.vstack((h,0.5*h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [94]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [93]:
##flatten
h.flatten()
h.flatten(order='C')
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [96]:
#raveㅣ
for i in h.ravel(order='C'):
  print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [97]:
for i in h.ravel(order='F'):
  print(i,end=' ')

0 3 6 9 12 1 4 7 10 13 2 5 8 11 14 

#bool 배열


In [98]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [101]:
h>5
h<=6
h==3

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [103]:
#true false를 0,1로 표현
(h==6).astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [106]:
(h>3)&(h<5)

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [107]:
#bool로 인덱싱하기
h[h>7]

array([ 8,  9, 10, 11, 12, 13, 14])

In [109]:
#np.where(case,true case,false case)
np.where(h%2==0,'even','odd')
np.where(h>5,1,0`)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#***STRUCTURED ARRAY***

In [112]:
#구조화 배열:열마다 여러 자료형 사용
#ndarray는 원래 단일 자료형 가능
dt=np.dtype([('Name','S10'),('age','i4'),
             ('height','f'),('childern','i4',1)])
dt

dtype([('Name', 'S10'), ('age', '<i4'), ('height', '<f4'), ('childern', '<i4', (1,))])